myApp/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index),
    path('index', views.index1),
    path('<int:num>/', views.detail),
    path('grades/', views.grades),
    path('students/', views.students),
    path('students1/', views.students1),
    path('stu/<int:page>/', views.students2),
    path('studentsearch', views.studentsearch),
    path('grades/<int:id>/', views.gradeStudents),
    path('addstudent/', views.addStudent),
    path('attribles/', views.attribles),
    path('get1/', views.get1),
    path('get2/', views.get2),
    path('showregist/', views.showregist),
    path('regist/', views.regist),
    path('showresponse/', views.showresponse),
    path('cookietest', views.cookietest),
    path('redirect1/', views.redirect1),
    path('redirect2/', views.redirect2),
    path('main/', views.main),
    path('login/', views.login),
    path('showmain/', views.showmain),
    path('quit/', views.quit),
    path('good/', views.good, name = 'good'),
    path('zhuye/', views.zhuye),
    path('detail/', views.detail),
    path('postfile/', views.postfile),
    path('showname/', views.showname, name='showname'),
    path('verifycode/', views.verifyCode, name='verifycode'),
    path('checkverifycode', views.checkverifycode, name='checkverifycode'),
    path('verifycodefile/', views.verifycodefile),
    path('upfile/', views.upfile),
    path('savefile/', views.savefile, name='savefile'),
    path('studentspage/<int:pageId>/', views.studentspage, name='studentspage'),
    path('ajaxstudents/', views.ajaxstudents),
    path('studentsinfo/', views.studentsinfo),
    path('edit/', views.edit),
    path('celerytest/', views.celerytest),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sunck/',include('myApp.urls', namespace='app')),
]

myApp/models.py
from django.db import models

# Create your models here.

class Grades(models.Model):
    # 自定义模型管理器
    # 当自定模型管理器，objects就不存在了
    # gradesObj = models.Manager()
    gname = models.CharField(max_length=20)
    gdate = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum = models.IntegerField()
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.gname
'''
    class Meta:
        db_table = ''
        ordering = []
'''


class StudentsManager(models.Manager):

    def get_queryset(self):
        return super(StudentsManager, self).get_queryset().filter(isDelete=False)

    def createStudent(self, name, gender, age, condent, grade, isD=False):
        stu = self.model()
        stu.sname = name
        stu.sgender = gender
        stu.sage = age
        stu.scondent = condent
        stu.sgrade = grade
        return stu


class Students(models.Model):
    stuObj = StudentsManager()
    sname = models.CharField(max_length=20)
    sgender = models.BooleanField(default=True)
    sage = models.IntegerField()
    scondent = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)
    sgrade = models.ForeignKey("Grades",on_delete=models.DO_NOTHING)    #关联外键

    def __str__(self):
        return self.sname

    @classmethod
    def createStudent(cls, name, gender, age, condent, grade, isD=False):
        student = cls(sname=name, sgender=gender, sage=age, scondent=condent, isDelete=isD, sgrade=grade)
        return student

from tinymce.models import HTMLField
class Text(models.Model):
    str1 = HTMLField()

myApp/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from .models import Students,Grades
from django.db.models import Max,F,Q
import sys

def index(request):
    g = Grades.objects.filter(gboynum__gt=F('ggirlnum'))
    print(g)
    return render(request, 'myApp/index.html')

def index1(request):
    return HttpResponseRedirect('/sunck')

def detail(request, num, num2):
    return HttpResponse('detail-%s-%s' %(num,num2))

def grades(request):
    #去模型里取数据
    gradesList = Grades.objects.all()
    #将数据传递给模板，模板再进行渲染页面，将渲染好的页面返回浏览器
    return render(request, 'myApp/grades.html', {'grades': gradesList})


def students(request):
    studentsList = Students.stuObj.all()
    return render(request, 'myApp/students.html', {'students': studentsList})

def students1(request):
    studentsList = Students.stuObj.all()[0:2]
    return render(request, 'myApp/students.html', {'students': studentsList})


def students2(request, page):
    studentsList = Students.stuObj.all()[(page-1)*2:page*2]
    return render(request, 'myApp/students.html', {'students': studentsList})


def studentsearch(request):
    maxAge = Students.stuObj.aggregate(Max('sage'))
    print(maxAge)
    studentsList = Students.stuObj.filter(Q(pk__lte=2) | Q(sage__gt=50))
    print(studentsList)
    # 学生描述中带有薛艳梅的学生所在班级的集合
    gradesList = Grades.objects.filter(students__scondent__contains='薛艳梅')
    print(gradesList)
    return HttpResponse('1111')

def gradeStudents(request, id):
    grade = Grades.objects.get(pk=id)
    studentsList = grade.students_set.all()
    return render(request, 'myApp/gradeStudents.html', {'students': studentsList,   \
    'grade': grade})


def addStudent(request):
    grade = Grades.objects.get(pk=1)
    stu = Students.createStudent("刘德华", True, 30, "我是刘德华", grade)
    stu.save()
    return HttpResponse('111')

def attribles(request):
    print(request.path)
    print(request.method)
    print(request.encoding)
    print(request.GET)
    print(request.POST)
    print(request.FILES)
    print(request.COOKIES)
    print(request.session)
    return HttpResponse('123123123123123')

def get1(request):
    a = request.GET.get('a')
    b = request.GET['b']
    c = request.GET.get('c')
    return HttpResponse(a +  "     "  + b + "   " + c)

def get2(request):
    aList = request.GET.getlist('a')
    a1 = aList[0]
    a2 = aList[1]
    b = request.GET.get('c')
    return HttpResponse(str(a1) + "   " + str(a2) + "   " + str(b))

def showregist(request):
    return render(request, 'myApp/regist.html')

def regist(request):
    name = request.POST.get('name')
    gender = request.POST.get('gender')
    age = request.POST.get('age')
    hobbyList = request.POST.getlist('hobby')
    print(name)
    print(gender)
    print(age)
    print(hobbyList)
    return HttpResponse('post')

def showresponse(request):
    res = HttpResponse(content=b'dawdafawdadadw')
    print(res.content)
    print(res.charset)
    print(res.status_code)
    return res

def cookietest(request):
    res = HttpResponse()
    # res.set_cookie('sunck', value='good', max_age=None, expires=None, path='/', domain=None, secure=False, httponly=False, samesite=None)
    cookies = request.COOKIES
    res.write('<h1>' + cookies['sunck'] + '</h1>')
    return res

def redirect1(request):
    # return HttpResponseRedirect('/sunck/redirect2/')
    return redirect('/sunck/redirect2')
def redirect2(request):
    return HttpResponse(content='我是重定向之后的页面')


#session
def main(request):
    username = request.session.get('name', '游客')
    return render(request, 'myApp/main.html', {'username': username})

def login(request):
    return render(request, 'myApp/login.html')

def showmain(request):
    username = request.POST.get('username')
    request.session['name'] = username
    return redirect('/sunck/main/')

from django.contrib.auth import logout
def quit(request):
    # 清除session
    # 推荐使用logout()
    logout(request)
    # request.session.clear()
    # request.session.flush()
    return redirect('/sunck/main/')


def good(request):
    return HttpResponse(content='good')

def zhuye(request):
    return render(request, 'myApp/index.html')

def detail(request):
    return render(request, 'myApp/detail.html')

def postfile(request):
    return render(request, 'myApp/postfile.html')

def showname(request):
    user = request.POST.get('username')
    pwd = request.POST.get('passwd')
    return render(request, 'myApp/showname.html', {'username': user, 'passwd': pwd})

def verifyCode(request):
    # 引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), random.randrange(20, 100))
    width = 100
    height = 50
    # 创建画面对象
    im = Image.new('RGB', (width, height), color=bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point（）函数绘制噪点
    for i in range(80):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str = '1234567890QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str[random.randrange(0, len(str))]
    # 构造字体对象
    font = ImageFont.truetype(font='/static/myApp/font/verdanab.ttf', size=40)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    draw.text((5, 2), rand_str[0], fill=fontcolor, font=font)
    draw.text((25, 2), rand_str[1], fill=fontcolor, font=font)
    draw.text((50, 2), rand_str[2], fill=fontcolor, font=font)
    draw.text((75, 2), rand_str[3], fill=fontcolor, font=font)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    # 内存文件操作
    import io
    buf = io.BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

def checkverifycode(request):
    userInput = request.POST.get('verifycode').upper()
    verifyCode = request.session['verifycode'].upper()
    if userInput == verifyCode:
        return HttpResponse(content='成功')
    else:
        request.session['flag'] = False
        return redirect('/sunck/verifycodefile')

def verifycodefile(request):
    f = request.session.get('flag', True)
    print(f)
    str1 = ''
    if f == False:
        str1 = '请重新输入'
    request.session.clear()
    return render(request, 'myApp/verifycodefile.html', {'flag': str1})

def upfile(request):
    return render(request, 'myApp/upfile.html')


import os
from django.conf import settings

def savefile(request):
    if request.method == 'POST':
        f = request.FILES['file']
        # 合成文件在服务器端的路径
        filepath = os.path.join(settings.MEDIA_ROOT, f.name)
        with open(filepath, 'wb') as fp:
            for info in f.chunks():
                fp.write(info)
        return HttpResponse(content='上传成功')
    else:
        return HttpResponse(content='上传失败')

from django.core.paginator import Paginator
def studentspage(request, pageId):
    allList = Students.stuObj.all()
    paginator = Paginator(allList, 2)
    page = paginator.page(pageId)
    return render(request, 'myApp/studentspage.html', {'students': page})

def ajaxstudents(request):
    return render(request, 'myApp/ajaxstudents.html')


from django.http import JsonResponse
def studentsinfo(request):
    stus = Students.stuObj.all()
    print(type(stus))
    list = []
    for stu in stus:
        list.append([stu.sname, stu.sage])
    return JsonResponse({"students": list})


def edit(request):
    return render(request, 'myApp/edit.html')

import time
from .task import task1
def celerytest(request):
    task1.delay()
    return render(request, 'myApp/celeryTest.html')

templates/myApp/ajaxstudents.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>学生信息列表</title>
    <script type="text/javascript" src="../../static/myApp/js/jquery-3.3.1.min.js">

    </script>
    </script>
  </head>
  <body>
    <h1>学生信息列表</h1>
    <button type="button" name="button" id="btn">显示学生信息</button>
    <script type="text/javascript" src="{% static 'myApp/js/changjiang.js' %}">
    </script>
  </body>
</html>

templates/myApp/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'myApp/css/style.css' %}">
    <style media="screen">
      #header {
        width: 100%;
        height: 100px;
        background-color: red;
      }
      #footer {
        width: 100%;
        height: 100px;
        background-color: blue;
      }
    </style>
  </head>
  <body>
    <div id="header">
      header
    </div>
    <div id="main">
      {% block main %}
      {% endblock main %}
    </div>
    <div id="footer">
      footer
    </div>
  </body>
</html>

templates/myApp/celeryTest.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>celery</title>
  </head>
  <body>
    <h1>celery页面</h1>
  </body>
</html>

templates/myApp/detail.html
{% extends 'myApp/base.html' %}

{% block main %}
  <h1>这是一个详情页</h1>
{% endblock main %}

templates/myApp/edit.html
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>富文本</title>
    <script type="text/javascript" src="../../static/tiny_mce/tiny_mce.js">
    </script>
    <script type="text/javascript">
      tinyMCE.init({
        'mode': 'textareas',
        'theme': 'advanced',
        'width': 800,
        'height': 600,
      });
    </script>
  </head>
  <body>
    <form class="" action="index.html" method="post">
      <textarea name="str" rows="8" cols="80">changjiang is a good man!</textarea>
    </form>
  </body>
</html>

templates/myApp/grades.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <title>班级信息</title>
    <link rel="stylesheet" href="/static/myApp/css/style.css">
  </head>
  <body>
    <h1>班级信息列表</h1>
    <ul>
      {%for grade in grades%}
      <li>
        <a href="{{grade.id}}">{{grade.gname}}</a>
      </li>
      {%endfor%}
    </ul>
  </body>
</html>

templates/myApp/index.html
{% extends 'myApp/base.html' %}
{% load static from staticfiles %}

{% block main %}
  <script type="text/javascript" src="{% static 'myApp/js/jquery-3.3.1.min.js' %}">
  </script>
  <script type="text/javascript" src="{% static 'myApp/js/changjiang.js' %}">

  </script>

  <h1>sunck is a good man</h1>
  <img src="{% static 'myApp/img/1.jpg' %}" alt="">
{% endblock main %}

templates/myApp/login.html
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>登陆</title>
  </head>
  <body>
    <form class="" action="/sunck/showmain/" method="post">
      <input type="text" name="username" value="">
      <input type="submit" name="" value="登陆">
    </form>
  </body>
</html>

templates/myApp/main.html
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>首页</title>
  </head>
  <body>
    <h1>欢迎： {{username}}</h1>
    <a href="/sunck/login/">登陆</a>
    <a href="/sunck/quit/">退出</a>
  </body>
</html>

templates/myApp/postfile.html
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="{% url 'app:showname' %}" method="post">
      {% csrf_token %}
      姓名:<input type="text" name="username" value="">
      <br>
      密码:<input type="password" name="passwd" value="">
      <br>
      <input type="submit" name="" value="登陆">
    </form>
  </body>
</html>

templates/myApp/regist.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>注册</title>
    </head>
    <body>
        <form action="/sunck/regist/" method="POST">
            姓名：<input type="text" name="name" id=""/>
            <hr/>
            性别：<input type="radio" name="gender" id="" value="1"/>男
                 <input type="radio" name="gender" value="0">女
            <hr/>
            年龄：<input type="text" name="age" id=""/>
            <hr/>
            爱好：<input type="checkbox" name="hobby" id="" value="power"/>权力
            <input type="checkbox" name="hobby" id="" value="money"/>金钱
            <input type="checkbox" name="hobby" id="" value="boy"/>美男
            <input type="checkbox" name="hobby" id="" value="girl"/>美女
            <hr/>
            <input type="submit" value="注册">

        </form>
    </body>
</html>

templates/myApp/showname.html
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{username}}--{{passwd}}</h1>
  </body>
</html>

templates/myApp/studentspage.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>学生分页显示</title>
    <link rel="stylesheet" href="{% static 'myApp/css/menu.css' %}">
  </head>
  <body>
    <ul>
      {% for stu in students %}
      <li>{{stu.sname}}--{{stu.sgrade}}</li>
      {% endfor %}
    </ul>

    <ul id="menu">
      {% for index in students.paginator.page_range %}
      {% if index == students.number %}
      <li>{{index}}</li>
      {% else %}
      <li>
        <a href="{% url 'app:studentspage' index %}">{{index}}</a>
      </li>
      {% endif %}

      {% endfor %}
    </ul>
  </body>
</html>

templates/myApp/upfile.html
<!DOCTYPE html>
<html lang="zh-CN" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>上传图片</title>
  </head>
  <body>
    <form class="" action="{% url 'app:savefile' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file" name="file" value="">
      <input type="submit" name="" value="上传图片">
    </form>
  </body>
</html>